version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    
    # This ensures all weekly non-security updates are bunched into ONE PR
    groups:
      weekly-updates:
        patterns:
          - "*"

    # Filters out minor noise to focus on meaningful updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
