language: node_js
node_js:
  - stable
cache:
  npm: true
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "jdasoftwaregroup"
script:
  - npm test:coverage:deploy
  - sonar-scanner
